# This script dynamically generates exported functions (and documentation)
# from dash's component metadata

library(jsonlite)
library(glue)

# -----------------------------------------------------------------------------
# First, handle the core components
# -----------------------------------------------------------------------------

core <- fromJSON(
  "https://raw.githubusercontent.com/plotly/dash-core-components/master/dash_core_components/metadata.json"
)

# remove line-breaks from strings
rm_linebreaks <- function(x) gsub("\n", " ", x, fixed = TRUE)
core <- rapply(core, rm_linebreaks, classes = "character", how = "replace")

# helper to get the actual name of the component from a component's filename
component_name <- function(x) {
  strsplit(basename(x), "\\.")[[1]][1]
}


# delete the current component definitions
unlink("R/components-core.R")

# auto-generate roxygen documentation and exported function for each *core* component
for (i in seq_along(core)) {
  component <- core[[i]]
  componentName <- component_name(names(core)[[i]])
  props <- component$props
  # we'll use ... for children instead
  props <- props[!names(props) %in% "children"]
  header <- glue(
    "# Auto-generated by inst/update_components.R -- do not edit by hand {linebreak} {linebreak}",
    "#' {title} core component {linebreak}#' @description {description} {linebreak}#' {linebreak}#' @export",
    "{linebreak} #' @param ... children of the component. Either other components or [htmltools::tags] are allowed.",
    title = componentName,
    description = component$description,
    linebreak = "\n"
  )
  body <- glue(
    "{linebreak}#' @param {name} {description} {required}",
    name = names(props),
    description = lapply(props, "[[", "description"),
    required = ifelse(sapply(props, "[[", "required"), "(required)", ""),
    linebreak = "\n"
  )
  # analogous to https://github.com/plotly/dash/blob/064c811/dash/development/base_component.py#L28-L37
  # TODO: how to incorporate required field? Also, automatic argument value checking?
  func <- glue(
    "

    core_*{name}* <- function(..., *{params}* = NULL) {

       component <- list(
         props = list(
           children = assert_valid_children(...),
           *{params2}*
         ),
         type = '*{type}*',
         namespace = 'dash_core_components'
       )

       component$props <- filter_null(component$props)

       structure(component, class = c('dash_component', 'core', '*{name}*', 'list'))
    }

    ",
    name = tolower(componentName),
    params = paste(names(props), collapse = " = NULL, "),
    params2 = paste(names(props), names(props), sep = "=", collapse = ", \n\t\t\t\t"),
    type = componentName,
    .open = "*{", .close = "}*"
  )

  cat(header, file = "R/components-core.R", append = TRUE)
  cat(body, file = "R/components-core.R", append = TRUE)
  cat(func, file = "R/components-core.R", append = TRUE)
}


# -----------------------------------------------------------------------------
# Now the HTML components
# -----------------------------------------------------------------------------

html <- fromJSON(
  "https://raw.githubusercontent.com/plotly/dash-html-components/master/lib/metadata.json"
)

html <- rapply(html, rm_linebreaks, classes = "character", how = "replace")

# delete the current component definitions
unlink("R/components-html.R")


# auto-generate roxygen documentation and exported function for each *core* component
for (i in seq_along(html)) {
  component <- html[[i]]
  componentName <- component_name(names(html)[[i]])
  props <- component$props
  # we'll use ... for children instead
  props <- props[!names(props) %in% "children"]
  header <- glue(
    "# Auto-generated by inst/update_components.R -- do not edit by hand {linebreak} {linebreak}",
    "#' {title} html component {linebreak}#' @description {description} {linebreak}#' {linebreak}#' @export",
    "{linebreak} #' @param ... children of the component. Either other components or [htmltools::tags()] are allowed.",
    title = tolower(componentName),
    description = if (nchar(component$description) > 0) component$description else paste0("See <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/", tolower(componentName), ">"),
    linebreak = "\n"
  )
  body <- glue(
    "{linebreak}#' @param {name} {description} {required}",
    name = names(props),
    description = lapply(props, "[[", "description"),
    required = ifelse(sapply(props, "[[", "required"), "(required)", ""),
    linebreak = "\n"
  )
  # TODO: automatic argument value checking?
  func <- glue(
    "

    html_*{name}* <- function(..., *{params}* = NULL) {

      component <- list(
         props = list(
           children = assert_valid_children(...),
           *{params2}*
         ),
         type = '*{type}*',
         namespace = 'dash_html_components'
       )

      component$props <- filter_null(component$props)

      structure(component, class = c('dash_component', 'html', '*{name}*', 'list'))
    }

    ",
    name = tolower(componentName),
    params = paste(names(props), collapse = " = NULL, "),
    params2 = paste(names(props), names(props), sep = "=", collapse = ", \n\t\t\t\t"),
    type = componentName,
    .open = "*{", .close = "}*"
  )

  cat(header, file = "R/components-html.R", append = TRUE)
  cat(body, file = "R/components-html.R", append = TRUE)
  cat(func, file = "R/components-html.R", append = TRUE)
}
