.dashR_js_metadata <- function() {
  deps_metadata <- list(`react-prod` = structure(list(name = "react",
                                                      version = "16.8.6",
                                                      src = list(href = "https://unpkg.com/react@16.8.6",
                                                                 file = "lib/react@16.8.6"),
                                                      meta = NULL,
                                                      script = "umd/react.production.min.js",
                                                      stylesheet = NULL,
                                                      head = NULL,
                                                      attachment = NULL,
                                                      package = "dashR",
                                                      all_files = FALSE),
                                                 class = "html_dependency"),
                        `react-dom-prod` = structure(list(name = "react-dom",
                                                          version = "16.8.6",
                                                          src = list(href = "https://unpkg.com/react-dom@16.8.6",
                                                                     file = "lib/react-dom@16.8.6"),
                                                          meta = NULL,
                                                          script = "dist/react-dom.production.min.js",
                                                          stylesheet = NULL,
                                                          head = NULL,
                                                          attachment = NULL,
                                                          package = "dashR",
                                                          all_files = FALSE),
                                                     class = "html_dependency"),
                        `dash-renderer-dev` = structure(list(name = "dash-renderer",
                                                         version = "0.23.0",
                                                         src = list(href = "https://unpkg.com/dash-renderer@0.23.0",
                                                                    file = "lib/dash-renderer@0.23.0"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.dev.js",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dashR",
                                                         all_files = FALSE),
                                                    class = "html_dependency"),
                        `dash-renderer-map-dev` = structure(list(name = "dash-renderer",
                                                         version = "0.23.0",
                                                         src = list(href = "https://unpkg.com/dash-renderer@0.23.0",
                                                                    file = "lib/dash-renderer@0.23.0"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.dev.js.map",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dashR",
                                                         all_files = FALSE),
                                                    class = "html_dependency"),
                        `dash-renderer-prod` = structure(list(name = "dash-renderer",
                                                         version = "0.23.0",
                                                         src = list(href = "https://unpkg.com/dash-renderer@0.23.0",
                                                                    file = "lib/dash-renderer@0.23.0"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.min.js",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dashR",
                                                         all_files = FALSE),
                                                    class = "html_dependency"),
                        `dash-renderer-map-prod` = structure(list(name = "dash-renderer",
                                                         version = "0.23.0",
                                                         src = list(href = "https://unpkg.com/dash-renderer@0.23.0",
                                                                    file = "lib/dash-renderer@0.23.0"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.min.js.map",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dashR",
                                                         all_files = FALSE),
                                                    class = "html_dependency")                        
                        )
  return(deps_metadata)
}
