.dashR_js_metadata <- function() {
  deps_metadata <- list(`react` = structure(list(name = "react",
                                               version = "15.4.2",
                                               src = list(href = "https://unpkg.com/react@15.4.2",
                                                          file = "lib/react@15.4.2"),
                                               meta = NULL,
                                               script = "dist/react.min.js",
                                               stylesheet = NULL,
                                               head = NULL,
                                               attachment = NULL,
                                               package = "dashR",
                                               all_files = FALSE),
                                          class = "html_dependency"),
                        `react-prod` = structure(list(name = "react",
                                                      version = "16.2.0",
                                                      src = list(href = "https://unpkg.com/react@16.2.0",
                                                                 file = "lib/react@16.2.0"),
                                                      meta = NULL,
                                                      script = "umd/react.production.min.js",
                                                      stylesheet = NULL,
                                                      head = NULL,
                                                      attachment = NULL,
                                                      package = "dashR",
                                                      all_files = FALSE),
                                                 class = "html_dependency"),
                        `react-dom` = structure(list(name = "react-dom",
                                                     version = "15.4.2",
                                                     src = list(href = "https://unpkg.com/react-dom@15.4.2",
                                                                file = "lib/react-dom@15.4.2"),
                                                     meta = NULL,
                                                     script = "dist/react-dom.min.js",
                                                     stylesheet = NULL,
                                                     head = NULL,
                                                     attachment = NULL,
                                                     package = "dashR",
                                                     all_files = FALSE),
                                                class = "html_dependency"),
                        `react-dom-prod` = structure(list(name = "react-dom",
                                                          version = "16.2.0",
                                                          src = list(href = "https://unpkg.com/react-dom@16.2.0",
                                                                     file = "lib/react-dom@16.2.0"),
                                                          meta = NULL,
                                                          script = "umd/react-dom.production.min.js",
                                                          stylesheet = NULL,
                                                          head = NULL,
                                                          attachment = NULL,
                                                          package = "dashR",
                                                          all_files = FALSE),
                                                     class = "html_dependency"),
                        `dash-renderer` = structure(list(name = "dash-renderer",
                                                         version = "0.18.0",
                                                         src = list(href = "https://unpkg.com/dash-renderer@0.18.0",
                                                                    file = "lib/dash-renderer@0.18.0"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.min.js",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dashR",
                                                         all_files = FALSE),
                                                    class = "html_dependency"),
                        `dash-renderer` = structure(list(name = "dash-renderer",
                                                         version = "0.18.0",
                                                         src = list(href = "https://unpkg.com/dash-renderer@0.18.0",
                                                                    file = "lib/dash-renderer@0.18.0"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.min.js.map",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dashR",
                                                         all_files = FALSE),
                                                    class = "html_dependency"))
  return(deps_metadata)
}
