.dash_js_metadata <- function() {
  deps_metadata <- list(`react-prod` = structure(list(name = "react",
                                                      version = "16.8.6",
                                                      src = list(href = "https://unpkg.com/react@16.8.6",
                                                                 file = "lib/react@16.8.6"),
                                                      meta = NULL,
                                                      script = "umd/react.production.min.js",
                                                      stylesheet = NULL,
                                                      head = NULL,
                                                      attachment = NULL,
                                                      package = "dash",
                                                      all_files = FALSE),
                                                 class = "html_dependency"),
                        `react-dom-prod` = structure(list(name = "react-dom",
                                                          version = "16.8.6",
                                                          src = list(href = "https://unpkg.com/react-dom@16.8.6",
                                                                     file = "lib/react-dom@16.8.6"),
                                                          meta = NULL,
                                                          script = "dist/react-dom.production.min.js",
                                                          stylesheet = NULL,
                                                          head = NULL,
                                                          attachment = NULL,
                                                          package = "dash",
                                                          all_files = FALSE),
                                                     class = "html_dependency"),
                        `polyfill-prod` = structure(list(name = "polyfill",
                                                    version = "7.7.0",
                                                    src = list(href = "https://unpkg.com/@babel/polyfill@7.7.0",
                                                               file = "lib/polyfill@7.7.0"),
                                                    meta = NULL,
                                                    script = "dist/polyfill.min.js",
                                                    stylesheet = NULL,
                                                    head = NULL,
                                                    attachment = NULL,
                                                    package = "dash",
                                                    all_files = FALSE),
                                               class = "html_dependency"),
                        `dash-renderer-dev` = structure(list(name = "dash-renderer",
                                                         version = "1.4.1",
                                                         src = list(href = "https://unpkg.com/dash-renderer@1.4.1",
                                                                    file = "lib/dash-renderer@1.4.1"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.dev.js",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dash",
                                                         all_files = FALSE),
                                                    class = "html_dependency"),
                        `dash-renderer-map-dev` = structure(list(name = "dash-renderer",
                                                         version = "1.4.1",
                                                         src = list(href = "https://unpkg.com/dash-renderer@1.4.1",
                                                                    file = "lib/dash-renderer@1.4.1"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.dev.js.map",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dash",
                                                         all_files = FALSE),
                                                    class = "html_dependency"),
                        `dash-renderer-prod` = structure(list(name = "dash-renderer",
                                                         version = "1.4.1",
                                                         src = list(href = "https://unpkg.com/dash-renderer@1.4.1",
                                                                    file = "lib/dash-renderer@1.4.1"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.min.js",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dash",
                                                         all_files = FALSE),
                                                    class = "html_dependency"),
                        `dash-renderer-map-prod` = structure(list(name = "dash-renderer",
                                                         version = "1.4.1",
                                                         src = list(href = "https://unpkg.com/dash-renderer@1.4.1",
                                                                    file = "lib/dash-renderer@1.4.1"),
                                                         meta = NULL,
                                                         script = "dash-renderer/dash_renderer.min.js.map",
                                                         stylesheet = NULL,
                                                         head = NULL,
                                                         attachment = NULL,
                                                         package = "dash",
                                                         all_files = FALSE),
                                                    class = "html_dependency"),
                        `prop-types-dev` = structure(list(name = "prop-types",
                                                          version = "15.7.2",
                                                          src = list(href = "https://unpkg.com/prop-types@15.7.2",
                                                                     file = "lib/prop-types@15.7.2"),
                                                          meta = NULL,
                                                          script = "prop-types/prop-types.js",
                                                          stylesheet = NULL,
                                                          head = NULL,
                                                          attachment = NULL,
                                                          package = "dash",
                                                          all_files = FALSE),
                                                     class = "html_dependency"),
                        `prop-types-prod` = structure(list(name = "prop-types",
                                                           version = "15.7.2",
                                                           src = list(href = "https://unpkg.com/prop-types@15.7.2",
                                                                      file = "lib/prop-types@15.7.2"),
                                                           meta = NULL,
                                                           script = "prop-types/prop-types.min.js",
                                                           stylesheet = NULL,
                                                           head = NULL,
                                                           attachment = NULL,
                                                           package = "dash",
                                                           all_files = FALSE),
                                                      class = "html_dependency")
                        )
  return(deps_metadata)
}
